import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { NotificationProvider } from "./context/NotificationProvider";
import { UserProvider } from "./context/UserProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <NotificationProvider>
            <div className="flex flex-col min-h-screen h-screen">
              <Navbar></Navbar>
              <div className="flex-grow flex">{children}</div>
              <Footer></Footer>
            </div>
          </NotificationProvider>
        </UserProvider>
      </body>
    </html>
  );
}
